=== mvcasillas/practicaLibreXML/biblioSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="codigoObjeto">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z]{3}[0-9]{4}[^\sA-Za-z0-9]{2}"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="fecha">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="2022"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="precio">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="100"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="persona">
    <xs:sequence>
        <xs:element name="nombre" minOccurs="1" maxOccurs="unbounded">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Za-zÁÉÍÓÚáéíóú]{2,}(\s[A-Z]\.)*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="apellido" minOccurs="1" maxOccurs="unbounded">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Za-zÁÉÍÓÚáéíóú]{2,}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="plataforma">
    <xs:restriction base="xs:string">
        <xs:enumeration value="PS1"/>
        <xs:enumeration value="PS2"/>
        <xs:enumeration value="PS3"/>
        <xs:enumeration value="PS4"/>
        <xs:enumeration value="PS5"/>
        <xs:enumeration value="NDS"/>
        <xs:enumeration value="N3DS"/>
        <xs:enumeration value="Wii"/>
        <xs:enumeration value="WiiU"/>
        <xs:enumeration value="Switch"/>
        <xs:enumeration value="PC"/>
        <xs:enumeration value="XBOX"/>
        <xs:enumeration value="XBOXOne"/>
    </xs:restriction>
</xs:simpleType>

    <xs:complexType name="libro">
        <xs:sequence>
            <xs:element name="codigoLibro" type="codigoObjeto"/>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="saga" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="autor" type="persona" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="precio" type="precio"/>
            <xs:element name="fecha" type="fecha"/>
        </xs:sequence>
    </xs:complexType>

<xs:complexType name="pelicula">
    <xs:sequence>
        <xs:element name="codigoPeli" type="codigoObjeto"/>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="saga" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="fecha" type="fecha"/>
        <xs:element name="director" type="persona" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="precio" type="precio"/>    
    </xs:sequence>
</xs:complexType>

<xs:complexType name="videojuego">
    <xs:sequence>
        <xs:element name="codigoVideojuego" type="codigoObjeto"/>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="saga" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="fecha" type="fecha"/>
        <xs:element name="plataforma" type="plataforma" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="precio" type="precio"/>    
    </xs:sequence>
</xs:complexType>

<!-- 
<xs:complexType name="objeto">
    <xs:choice>
        <xs:element name="libro"/>
        <xs:element name="pelicula"/>
        <xs:element name="videojuego"/>
    </xs:choice>
</xs:complexType> -->

<xs:simpleType name="codigoSocio">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z]{3}[0-9]{4}[^\sA-Za-z0-9]"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="dni">
    <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{8}[A-Z]"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="socio">
            <xs:sequence>
                <xs:element name="codigoSocio" type="codigoSocio"/>
                <xs:element name="dni" type="dni"/>
                <xs:element name="nombreCompleto" type="persona"/>
                <xs:element name="edad">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="12"/>
                            <xs:maxInclusive value="150"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="genero">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="masculino|femenino|neutro"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="fechaAlta">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{2}\-[0-9]{2}\-[0-9]{4}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
        </xs:sequence>
</xs:complexType>


<xs:element name="biblioteca">
    <xs:complexType>
        <xs:all>
            <xs:element name="objetosEnPrestamo">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="libro" type="libro" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="pelicula" type="pelicula" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="videojuego" type="videojuego" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="socios">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="socio" type="socio" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:element>

</xs:schema>

=== mvcasillas/practicaLibreXML/biblioteca2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="biblioXSL.xsl"?>
<!DOCTYPE biblioteca>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="biblioSchema.xsd">

    <objetosEnPrestamo>
        <libro>
            <codigoLibro>SCI8564*¿</codigoLibro>
            <titulo>Los juegos del hambre</titulo>
            <saga>Los juegos del hambre</saga>
            <autor>
                <nombre>Suzanne</nombre>
                <apellido>Collins</apellido>
            </autor>
            <precio>15.50</precio>
            <fecha>2008</fecha>
        </libro>
        <libro>
            <codigoLibro>SCI8565*!</codigoLibro>
            <titulo>En llamas</titulo>
            <saga>Los juegos del hambre</saga>
            <autor>
                <nombre>Suzanne</nombre>
                <apellido>Collins</apellido>
            </autor>
            <precio>15.50</precio>
            <fecha>2009</fecha>
        </libro>
        <libro>
            <codigoLibro>SCI8566!¿</codigoLibro>
            <titulo>Sinsajo</titulo>
            <saga>Los juegos del hambre</saga>
            <autor>
                <nombre>Suzanne</nombre>
                <apellido>Collins</apellido>
            </autor>
            <precio>15.50</precio>
            <fecha>2010</fecha>
        </libro>
        
        <libro>
            <codigoLibro>FAN1445+)</codigoLibro>
            <titulo>Harry Potter y la Piedra Filosofal</titulo>
            <saga>Harry Potter</saga>
            <autor>
                <nombre>J. K.</nombre>
                <apellido>Rowling</apellido>
            </autor>
            <precio>15</precio>
            <fecha>1997</fecha>
        </libro>
        
        <pelicula>
            <codigoPeli>ANI8872!!</codigoPeli>
            <titulo>Red</titulo>
            <fecha>2022</fecha>
            <director>
                <nombre>Domee</nombre>
                <apellido>Shi</apellido>
            </director>
            <precio>11.99</precio>
        </pelicula>
        <pelicula>
            <codigoPeli>ANI8879.*</codigoPeli>
            <titulo>Coco</titulo>
            <fecha>2017</fecha>
            <director>
                <nombre>Adrián</nombre>
                <apellido>Molina</apellido>
            </director>
            <director>
                <nombre>Lee</nombre>
                <nombre>Edward</nombre>
                <apellido>Unkrich</apellido>
            </director>
            <precio>11.99</precio>
        </pelicula>
        
        <videojuego>
            <codigoVideojuego>SIM0496ª!</codigoVideojuego>
            <titulo>Story of Seasons: Trio of towns</titulo>
            <saga>Harvest Moon</saga>
            <fecha>2016</fecha>
            <plataforma>N3DS</plataforma>
            <precio>19.90</precio>
        </videojuego>
        <videojuego>
            <codigoVideojuego>RPG8993()</codigoVideojuego>
            <titulo>Leyendas Pokémon: Arceus</titulo>
            <saga>Pokémon</saga>
            <fecha>2022</fecha>
            <plataforma>Switch</plataforma>
            <precio>45.90</precio>
        </videojuego>
        

    </objetosEnPrestamo>

    <socios>
        <socio>
            <codigoSocio>LOL8888-</codigoSocio>
            <dni>12345678B</dni>
            <nombreCompleto>
                <nombre>María</nombre>
                <nombre>José</nombre>
                <apellido>García</apellido>
                <apellido>Pérez</apellido>
            </nombreCompleto>
            <edad>28</edad>
            <genero>femenino</genero>
            <fechaAlta>15-02-2020</fechaAlta>
        </socio>
    </socios>
</biblioteca>
